---
include:
  - remote: https://gitlab.int.catalystcloud.nz/catalystcloud/gitlab-build-tools/raw/main/templates/docker-setup.gitlab-ci.yml

stages:
  - template
  - package
  - publish

.helm_publish_jobs:
  image: gitlab.int.catalystcloud.nz:4567/catalystcloud/helm-environment:20231218T191550Z
  before_script:
    - cd ${CI_PROJECT_DIR}/charts/openstack-cluster
    - export CHART_VERSION=$(git describe --tags)
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME =~ /^\d+\.\d+\.\d+.*$/

helm_package:
  extends: .helm_publish_jobs
  stage: package
  script:
    - helm dependency build ${CI_PROJECT_DIR}/charts/openstack-cluster
    - helm package --app-version $(git describe --always) --version ${CHART_VERSION}
      ${CI_PROJECT_DIR}/charts/openstack-cluster
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/charts/openstack-cluster/openstack-cluster-*.tgz"

.publish_chart:
  extends: .helm_publish_jobs
  stage: publish
  script:
    # NOTE(travis) push to both gitlab helm repo and OCI for now. Since OCI has no search function it might be useful
    # to have a place to browse packages.
    - >
      curl --request POST
      --form chart=@${CI_PROJECT_DIR}/charts/openstack-cluster/openstack-cluster-${CHART_VERSION}.tgz
      --user gitlab-ci-token:${CI_JOB_TOKEN}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/${HELM_CHANNEL}/charts
    - >
      helm push
      ${CI_PROJECT_DIR}/charts/openstack-cluster/openstack-cluster-${CHART_VERSION}.tgz
      oci://internal.oci-registry.nz-por-1.catalystcloud.nz/capi-helm-charts
  dependencies:
    - helm_package
# NOTE(travis) Alternately publish chart to "dev" or "stable" channel depending if commit tag is on the default branch.
publish_chart_dev:
  extends: .publish_chart
  variables:
    HELM_CHANNEL: dev
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_NAME =~ /^\d+\.\d+\.\d+.*$/

publish_chart_prod:
  extends: .publish_chart
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_NAME =~ /^\d+\.\d+\.\d+.*$/
  variables:
    HELM_CHANNEL: stable
