---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackCluster
metadata:
  name: {{ include "openstack-cluster.clusterName" . }}
  labels: {{ include "openstack-cluster.labels" . | nindent 4 }}
  annotations:
    # We let Cluster API clean up this resource
    # Deleting it ourselves, which CAPI is not expecting, can cause some nasty race conditions
    helm.sh/resource-policy: keep
    # NOTE: Argo won't delete this object itself as it has an owner reference to the cluster
spec:
  identityRef:
    kind: Secret
    name: {{ include "openstack-cluster.cloudCredentialsSecretName" . }}
  cloudName: openstack
  {{- with .Values.controlPlaneEndpoint }}
  controlPlaneEndpoint: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.clusterNetworking }}
  {{- with .dnsNameservers }}
  dnsNameservers: {{ toYaml . | nindent 4 }}
  {{- end }}
  managedSecurityGroups: {{ .manageSecurityGroups }}
  allowAllInClusterTraffic: {{ .allowAllInClusterTraffic }}
  {{- with .externalNetworkId }}
  externalNetworkId: {{ . }}
  {{- end }}
  {{- with .internalNetwork }}
  {{- if or .networkFilter .subnetFilter }}
  {{- with .networkFilter }}
  network: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .subnetFilter }}
  subnet: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- else }}
  nodeCidr: {{ .nodeCidr }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- with .Values.apiServer }}
  {{- if .enableLoadBalancer }}
  apiServerLoadBalancer:
    enabled: true
  {{- if .loadBalancerProvider }}
    provider: {{ .loadBalancerProvider }}
  {{- end }}
  {{- if .allowedCidrs }}
    allowedCidrs:
      {{- range .allowedCidrs }}
      - {{ . }}
      {{- end}}
  {{- end }}
  {{- end }}

  disableAPIServerFloatingIP: {{ not .associateFloatingIP }}
  {{- with .floatingIP }}
  apiServerFloatingIP: {{ . }}
  {{- end }}
  {{- with .fixedIP }}
  apiServerFixedIP: {{ . }}
  {{- end }}
  apiServerPort: {{ .port }}
  {{- end }}
  {{- with .Values.controlPlane }}
  {{- if .omitFailureDomain }}
  controlPlaneOmitAvailabilityZone: true
  {{- else if .failureDomains }}
  controlPlaneAvailabilityZones: {{ toYaml .failureDomains | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.managementLoadBalancer }}
  managementLoadBalancer:
    cloudName: {{ .cloudName }}
    enabled: {{ .enabled }}
    identityRef:
      # This account needs to authenticate so it can create a loadbalancer in the same project
      # as the subnet given below.
      # It also needs `admin` role to attach members to any neutron network in another project.
      kind: Secret
      name: {{ .cloudCredentialsAdminSecretName }}
    additionalPorts:
      - 22
    provider: amphora
    subnet: {{ toYaml .subnet | nindent 6 }}
    network: {{ toYaml .network | nindent 6 }}
  {{- end }}
